#!/usr/bin/env python3
#
# Copyright (C) 2019
#

__author__    = 'Mobidic'
__authors__   = ['Henri Pegeot','David Baux','Kevin Yauy','Charles Van Goethem','Thomas Guignard','Olivier Ardouin']
__copyright__ = 'Copyright (C) 2019'
__license__   = 'GNU General Public License v3 (GPLv3)'
__version__   = '1.3a1'
__email__     = 'henri.pegeot@ext.inserm.fr'
__status__    = 'dev'

################################################################################
#
# IMPORT
#
################################################################################
import vcf        # read vcf => PyVCF :https://pyvcf.readthedocs.io/en/latest/
import sys        # system command
import os         # os command
import re         # regex
import argparse   # for options
import logging    # logging messages
import subprocess # launch subprocess
import collections
import mobidic_mobicnv


if __name__ == "__main__":
    mobidic_mobicnv.main()
